server:
  port: 8181

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/sapientdb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    
logging:
  level:
    root: WARN
    '[com.zaxxer.hikari]': DEBUG 